# Generated by Django 5.0.1 on 2024-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualdate',
            name='table',
            field=models.FileField(upload_to=''),
        ),
    ]
