# Generated by Django 5.0.1 on 2024-01-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0003_visualdategeography_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualDateSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('table', models.FileField(upload_to='')),
            ],
        ),
    ]
