# Generated by Django 5.0.1 on 2024-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0005_animatedskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetHHVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
