# Generated by Django 5.0.1 on 2024-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0006_gethhvacancies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetHHVacancies',
        ),
    ]
